export const GET_BOOKS_BY_TITLE = "GET_BOOKS_BY_TITLE";
export const GET_BOOKS_BY_AUTHOR = "GET_BOOKS_BY_AUTHOR";
export const GET_NEWS_ARTICLES = "GET_NEWS_ARTICLES";
export const GET_RESEARCH_ARTICLES = "GET_RESEARCH_ARTICLES";
export const GET_VIDEOS = "GET_VIDEOS";
export const BOOKS_ERROR = "BOOKS_ERROR";
export const ARTICLES_ERROR = "ARTICLES_ERROR";
export const SAVE_ERROR = "SAVE_ERROR";
export const VIDEOS_ERROR = "VIDEOS_ERROR";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SUCCESS_STATUS = "SUCCESS_STATUS";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const ADD_RESEARCH_ARTICLE = "ADD_RESEARCH_ARTICLE";
export const GET_SAVED_RESEARCH_ARTICLES = "GET_SAVED_RESEARCH_ARTICLES";
export const RESEARCH_ARTICLES_ERROR = "RESEARCH_ARTICLES_ERROR";
export const REMOVE_RESEARCH_ARTICLE = "REMOVE_RESEARCH_ARTICLE";
export const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";

export const ADD_NEWS_ARTICLE = "ADD_NEWS_ARTICLE";
export const GET_SAVED_NEWS_ARTICLES = "GET_SAVED_NEWS_ARTICLES";
export const NEWS_ARTICLES_ERROR = "NEWS_ARTICLES_ERROR";
export const REMOVE_NEWS_ARTICLE = "REMOVE_NEWS_ARTICLE";
export const DELETE_ERROR = "DELETE_ERROR";
export const ADD_BOOKS = "ADD_BOOKS";
export const GET_SAVED_BOOKS = "GET_SAVED_BOOKS";
export const SAVE_BOOKS_ERROR = "SAVE_BOOKS_ERROR";
export const SAVE_NEWS_ERROR = "SAVE_NEWS_ERROR";
export const SAVE_RESEARCH_ERROR = "SAVE_RESEARCH_ERROR";
export const REMOVE_BOOK = "REMOVE_BOOK";

export const FILTER_SAVED_BOOKS = "FILTER_SAVED_BOOKS";
export const CLEAR_FILTERED_BOOKS = "CLEAR_FILTERED_BOOKS";

export const FILTER_SAVED_NEWS_ARTICLES = "FILTER_SAVED_NEWS_ARTICLES";
export const CLEAR_FILTERED_NEWS_ARTICLES = "CLEAR_FILTERED_NEWS_ARTICLES";

export const FILTER_SAVED_RESEARCH_ARTICLES = "FILTER_SAVED_RESEARCH_ARTICLES";
export const CLEAR_FILTERED_RESEARCH_ARTICLES =
  "CLEAR_FILTERED_RESEARCH_ARTICLES";

export const DELETE_SAVED_BOOK = "DELETE_SAVED_BOOK";
export const DELETE_SAVED_NEWS_ARTICLE = "DELETE_SAVED_NEWS_ARTICLE";
export const DELETE_SAVED_RESEARCH_ARTICLE = "DELETE_SAVED_RESEARCH_ARTICLE";
