export const GET_BOOKS_BY_TITLE = "GET_BOOKS_BY_TITLE";
export const GET_BOOKS_BY_AUTHOR = "GET_BOOKS_BY_AUTHOR";
export const GET_NEWS_ARTICLES = "GET_NEWS_ARTICLES";
export const GET_RESEARCH_ARTICLES = "GET_RESEARCH_ARTICLES";
export const GET_VIDEOS = "GET_VIDEOS";
export const BOOKS_ERROR = "BOOKS_ERROR";
export const ARTICLES_ERROR = "ARTICLES_ERROR";
export const VIDEOS_ERROR = "VIDEOS_ERROR";
